### PR TITLE
core framework seems not to depend on asm

### PR DESCRIPTION
**Pull request by kontext-e**
Part 2 from former PR: remove ASM dependency

### CODE REVIEW

**Comment by DirkMahler** [comment]
AFAIK Asciidoctor depends on ASM. The jQA Java plugin has a direct dependeny to ASM and those versions need to be synchronized as core and plugins share the same classloader (at least in the Maven plugin). So if the Java plugin gets an upgrade it must be verified if the whole stack still works. The correct solution BTW would be a clear isolation of the plugins.

**Comment by kontext-e** [comment]
But shoudn't Asciidoctor bring it's own dependencies and Maven resolve to the highest Version number?

**Comment by kontext-e** [comment]
mvn asciidoctor:process-asciidoc works as expected, should I try other Things to verify whether the whole stack works?

**Comment by kontext-e** [comment]
Already done with commit 5fc5a41c6ce94c1ccc1f4cd099ecd3618bb45f28

**Pull request closed without merging**
