### PR TITLE
in case of constraint violation, print also the number of found violations

### PR DESCRIPTION
**Pull request by kontext-e**

### CODE REVIEW

**Comment by kontext-e** [comment]
Tried to create a new pull request, but was added to this one:
updated asm version to 6.1 to support Java 9

**Comment by kontext-e** [comment]
Did a mvn clean install without asm dependencies, worked so far. Maybe dependency can be removed completely.

**Comment by obfischer** [comment]
Could you please remove the Java 9 commit from this PR and create a separate one for it?

**Comment by kontext-e** [comment]
Split up into two other PRs.

**Pull request closed without merging**
